# Generated by Django 5.0.14 on 2026-08-08 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ref_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('doctor_id', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_specialty', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reason', models.TextField(blank=True, default='')),
                ('payment_type', models.CharField(default='Private Self-Pay', max_length=100)),
                ('hmo_name', models.CharField(blank=True, default='N/A', max_length=200)),
                ('hmo_policy_code', models.CharField(blank=True, default='', max_length=100)),
                ('hmo_auth_code', models.CharField(blank=True, default='', max_length=100)),
                ('referral_doc_name', models.CharField(blank=True, default='', max_length=200)),
                ('hmo_status', models.CharField(default='N/A', max_length=100)),
                ('payment_status', models.CharField(default='Pending', max_length=100)),
                ('payment_method', models.CharField(blank=True, default='POS / Cash', max_length=100)),
                ('invoice_ref', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='Confirmed', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_name', models.CharField(default='Stethoscope', max_length=100)),
                ('doctor_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Public display name / acronym (e.g. Specialist A)', max_length=200)),
                ('full_name', models.CharField(blank=True, default='', help_text='Full real name for Admin (e.g. Dr. Adewale Olusola)', max_length=200)),
                ('acronym', models.CharField(blank=True, default='', help_text='Saved acronym (e.g. Specialist A)', max_length=50)),
                ('specialty', models.CharField(max_length=200)),
                ('department_id', models.CharField(default='pediatrics', max_length=100)),
                ('qualification', models.CharField(default='MBBS, FWACS', max_length=250)),
                ('qualifications', models.CharField(default='MBBS, FWACS', max_length=250)),
                ('available_days', models.JSONField(blank=True, default=list)),
                ('time_slots', models.JSONField(blank=True, default=list)),
                ('image', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='Senior Medical Consultant specializing in high-quality clinical care at Isalu Hospitals.')),
                ('room_number', models.CharField(default='Consultation Suite 4B', max_length=100)),
            ],
            options={
                'ordering': ['doc_id'],
            },
        ),
        migrations.CreateModel(
            name='HmoCompany',
            fields=[
                ('hmo_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=200)),
                ('status', models.CharField(default='Active Partner', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistSchedule',
            fields=[
                ('sched_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('doctor_id', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
                ('room', models.CharField(default='Consultation Suite', max_length=200)),
                ('duty_days', models.JSONField(default=list)),
                ('shift_time', models.CharField(default='08:00 AM – 02:00 PM', max_length=100)),
                ('capacity', models.IntegerField(default=15)),
                ('status', models.CharField(default='Active On Duty', max_length=100)),
            ],
            options={
                'ordering': ['sched_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(default='Helpdesk Officer', max_length=100)),
                ('desk', models.CharField(default='Helpdesk Reception', max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('last_active', models.CharField(default='Just now', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
