# Generated by Django 5.0.14 on 2026-08-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customtimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='password',
            field=models.CharField(default='admin123', max_length=255),
        ),
    ]
