# Generated by Django 5.0.14 on 2026-08-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_doctor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistschedule',
            name='day_configs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='specialistschedule',
            name='total_weekly_capacity',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='specialistschedule',
            name='shift_time',
            field=models.TextField(blank=True, default='08:00 AM – 02:00 PM'),
        ),
    ]
