# Generated by Django 5.0.14 on 2026-08-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_specialistschedule_day_configs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='accepted_patient_types',
            field=models.JSONField(blank=True, default=list, help_text="Accepted patient categories e.g. ['Private Self-Pay', 'HMO Insurance']"),
        ),
    ]
