# Generated by Django 5.0.14 on 2026-08-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_doctor_accepted_patient_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(blank=True, default='Main Building', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
