# Generated by Django 5.0.14 on 2026-08-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_department_location_department_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delete_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
