# Generated by Django 5.0.14 on 2026-08-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_booking_delete_reason_booking_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hmo_status',
            field=models.TextField(blank=True, default='N/A'),
        ),
    ]
