# Generated by Django 5.0.14 on 2026-08-26 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_booking_hmo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('primary_desk', models.CharField(default='helpdesk', max_length=100)),
                ('allowed_desks', models.JSONField(blank=True, default=list)),
                ('is_system_role', models.BooleanField(default=False)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
