# Generated by Django 5.0.14 on 2026-08-26 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_systemuser_auth_user_systemuser_role_ref'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('desk', models.CharField(default='Helpdesk Reception', max_length=100)),
                ('last_active', models.CharField(default='Just now', max_length=100)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='api.role')),
            ],
            options={
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
