# Generated by Django 5.0.14 on 2026-08-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofile_delete_systemuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='desk',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_active',
        ),
    ]
