# Generated by Django 5.0.14 on 2026-08-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_userprofile_desk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department_id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='api.department'),
        ),
    ]
