# Generated by Django 5.0.14 on 2026-08-26 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_doctor_department_id_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistschedule',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='specialistschedule',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='api.doctor'),
        ),
    ]
