# Generated by Django 5.0.14 on 2026-08-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_specialistschedule_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hmocompany',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='specialistschedule',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
