# Generated by Django 5.2.17 on 2026-08-31 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_appsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='time_slots',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='accepted_patient_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='acronym',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Full real name for Admin', max_length=200),
        ),
        migrations.AlterField(
            model_name='specialistschedule',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='specialistschedule',
            name='doctor_name',
            field=models.CharField(blank=True, default='Unassigned Doctor', max_length=200),
        ),
        migrations.AlterField(
            model_name='specialistschedule',
            name='specialty',
            field=models.CharField(blank=True, default='General Medicine', max_length=200),
        ),
    ]
