# Generated by Django 5.2.17 on 2026-08-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_doctor_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ref_code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
