# Generated by Django 5.2.17 on 2026-08-31 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_booking_id_alter_booking_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='doctor_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(db_index=True, default='Confirmed', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='doctor_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialistschedule',
            name='capacity',
            field=models.PositiveIntegerField(default=15, help_text='Maximum number of active appointments this doctor can accept per day.'),
        ),
        migrations.AlterField(
            model_name='specialistschedule',
            name='total_weekly_capacity',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['doctor_id', 'date'], name='booking_doctor_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['doctor_id', 'date', 'is_active'], name='booking_doctor_active_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['doctor_id', 'date', 'time'], name='booking_doctor_time_idx'),
        ),
    ]
