# Generated by Django 5.2.17 on 2026-09-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_booking_id_booking_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='referral_doc_text',
        ),
        migrations.AddField(
            model_name='booking',
            name='referral_doc',
            field=models.FileField(blank=True, null=True, upload_to='referrals/'),
        ),
    ]
