# Generated by Django 5.2.17 on 2026-09-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_booking_referral_doc_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='referral_doc',
            new_name='referral_doc_text',
        ),
    ]
