# Generated by Django 5.2.17 on 2026-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_referral_doc_booking_referral_doc_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='referral_doc_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
