# Generated by Django 5.0.14 on 2026-10-05 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_booking_referral_doc_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('exception_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('original_date', models.CharField(db_index=True, max_length=10)),
                ('action', models.CharField(choices=[('cancel', 'Cancel clinic'), ('reschedule', 'Move clinic to another date')], max_length=20)),
                ('new_date', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('shift_times', models.JSONField(blank=True, default=list)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True, default='')),
                ('affected_refs', models.JSONField(blank=True, default=list)),
                ('affected_count', models.PositiveIntegerField(default=0)),
                ('notification_status', models.CharField(default='pending', max_length=20)),
                ('notified_count', models.PositiveIntegerField(default=0)),
                ('notification_failed_count', models.PositiveIntegerField(default=0)),
                ('notification_log', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='api.doctor')),
            ],
            options={
                'ordering': ['original_date', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='scheduleexception',
            constraint=models.UniqueConstraint(fields=('doctor', 'original_date'), name='unique_exception_per_doctor_date'),
        ),
    ]
